brew "chezmoi"
brew "codex"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "lazygit"
brew "luarocks"
brew "neovim"
brew "node"
brew "pandoc"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "uv"
cask "claude-code"

{{ if eq .chezmoi.os "darwin" }}
brew "mas"
cask "chatgpt"
cask "clash-verge-rev"
cask "font-maple-mono-nf-cn"
cask "iterm2"
cask "itermai"
cask "spotify"
mas "Immersive Translate", id: 6447957425
mas "Infuse", id: 1136220934
mas "Lark", id: 6449830127
mas "The Unarchiver", id: 425424353
mas "uBlock Origin Lite", id: 6745342698
mas "Userscripts", id: 1463298887
mas "Vimlike", id: 1584519802
mas "WeChat", id: 836500024
mas "Windows App", id: 1295203466
mas "WPS Office", id: 1468073139
{{ end }}
